---
# tasks file for cockroachdb

- name: Create the cockroach user
  user:
      name: cockroach
      create_home: no
      shell: /bin/false

- name: Create the cockroach group
  group:
      name: cockroach

- name: Create cockroachDB directories
  file:
    path: "{{ item }}"
    state: directory
    owner: cockroach
    group: cockroach
    mode: 0755
  loop:
    - "{{ cockroachdb_path }}"
    - "{{ cockroachdb_path }}/bin"

- name: Download and extract the binary
  unarchive:
    src: "https://binaries.cockroachdb.com/cockroach-v{{ cockroachdb_version }}.linux-{{ cockroachdb_arch }}.tgz"
    dest: "{{ cockroachdb_path }}"
    remote_src: yes

- name: Copy the binary into the bin directory
  copy:
      remote_src: yes
      src: "{{ cockroachdb_path }}/cockroach-v{{ cockroachdb_version }}.linux-{{ cockroachdb_arch }}/cockroach"
      dest: "{{ cockroachdb_path }}/bin/cockroach"
      owner: cockroach
      mode: 0755

- name: Copy the service definition file
  template:
      src: cockroach.service
      dest: /etc/systemd/system/cockroach.service
      mode: 0664
  notify:
    - restart CockroachDB

- block:
  - import_tasks: certs.yml
  when: cockroachdb_secure

